#!/bin/bash

# Script to update the Ubuntu MOTD banner in /var/run/motd.dynamic
# motd.dynamic is generated by running scripts in /etc/update-motd.d/

# Step 1: Replace the first script in update-motd.d with our ASCII banner
cat > /etc/update-motd.d/00-custom-banner << 'SCRIPT'
#!/bin/bash
echo ""
echo "##############################################################"
echo "#                                                            #"
echo "#    ___  ______ _   _ _   _ _______ _    _                 #"
echo "#   / _ \ \___  / | | | \ | |__   __| |  | |               #"
echo "#  / /_\ \   / /| | | |  \| |  | |  | |  | |               #"
echo "#  |  _  |  / / | | | | . \` |  | |  | |  | |               #"
echo "#  | | | | / /__| |_| | |\  |  | |  | |__| |               #"
echo "#  \_| |_//_____|\___/\_| \_/  \_/   \____/                 #"
echo "#                                                            #"
echo "#          H O S T E D   O N   A Z U R E                    #"
echo "#                                                            #"
echo "##############################################################"
echo "#  WARNING: Authorized access only. All activity is logged. #"
echo "##############################################################"
echo ""
echo "  Hostname : $(hostname)"
echo "  IP Addr  : $(hostname -I | awk '{print $1}')"
echo "  OS       : $(lsb_release -d | cut -f2)"
echo "  Kernel   : $(uname -r)"
echo "  Uptime   : $(uptime -p)"
echo "  Users    : $(who | wc -l) logged in"
echo ""
SCRIPT

# Step 2: Make the script executable
chmod +x /etc/update-motd.d/00-custom-banner

# Step 3: Regenerate /var/run/motd.dynamic immediately
run-parts /etc/update-motd.d/ > /var/run/motd.dynamic

echo "Banner updated successfully in /var/run/motd.dynamic!"
echo "Verify with: cat /var/run/motd.dynamic"
